name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Get public IP of githubactions-server
        id: ec2
        run: |
          INSTANCE_IP=$(aws ec2 describe-instances \
            --region eu-north-1 \
            --filters "Name=tag:Name,Values=githubactions-server" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

      - name: Connect via SSH and run script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ubuntu  # or ec2-user, depending on AMI
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ Connected to EC2!"
