name: third-workflow
on:
  push:
    branches: ['main']
  pull_request: 
    branches: ['main']
  workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: basic commands
         run: |
            echo Thsi is build job
   test:
      runs-on: ubuntu-latest
      needs: build
      steps: 
        - name: test job
          run: |
            echo This is test job
   deploy:
       runs-on: ubuntu-latest
       needs: test
       steps: 
        - name: deploy job
          run: |
            echo This is deploy job
    
  
  
