name: Terraform VPC Deployment

on:
  workflow_dispatch:   # Allows manual trigger
  push:
    paths:
      - 'terraform/aws-vpc/**'   # Only trigger when VPC code changes
    branches:
      - main

jobs:
  terraform-vpc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5  # Or whatever you're using

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        working-directory: terraform/aws-vpc
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/aws-vpc
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/aws-vpc
        run: terraform apply -auto-approve
